### ISSUE TITLE
Add panel resizing

### ISSUE THREAD

**Issue by louisdh** [louisdh/panelkit#12]

**Comment by hy9be** [comment]
@louisdh hey do you still plan to work on it? Or you want to shed some lights for others to contribute? I am interested to make it happen. But I think you are the one would provide the best design.

**Comment by louisdh** [comment]
@hy9be Sorry for the late response! 
I've just pushed panel resizing (a5686d76b660bd1adb2dcea283c59464c400bb03). After much prototyping, I ended up going with one "resize handle" in the bottom right corner of each panel ([as previewed on Twitter](https://twitter.com/LouisDhauwe/status/915658275122745344)).

I'll probably write a blog post about the other options for resizing I tried, someday 🙂.

**Comment by louisdh** [comment]
I've also pushed a prototype of a "resize mode" on the `resize-mode` branch (f3629f762d9e05811a77434df3e016d5fcb722fa). The mode is entered by double tapping twice on a panel, after which four handles appear to resize. There's also support for resizing via pinching in or out.

**Comment by hy9be** [comment]
@louisdh Gave it a try. Works great!

The only thing is that I had to trace the code and add the following code to make it work. Otherwise the two sizes are the same with preferred size, which cancels any resizing actions. Do you want to document it or set some other default values?

```swift
    var minimumPanelContentSize: CGSize {
        return CGSize(width: 1.0, height: 1.0)
    }
    
    var maximumPanelContentSize: CGSize {
        return UIScreen.main.bounds.size
    }
```

**Comment by louisdh** [comment]
@hy9be I still need to hide the handle when `minimumPanelContentSize` and `maximumPanelContentSize` are the panel's preferred size (which indeed disables any resizing). The current default values are by design, so by default resizing is disabled for all panels. 

I will definitely add some documentation for these properties. And should probably make a guide for adding resizing as a whole. Thanks for giving it a try!

**Comment by louisdh** [comment]
@hy9be I've added the logic to show and hide the handle when appropriate in cb6b8a49af3252d6f750a9ec43fdf63448ddd020.
