### ISSUE TITLE
Close single panel?

### ISSUE THREAD

**Issue by barrettj** [louisdh/panelkit#14]
The close method on PanelManager isn't public so I can't choose to close an individual panel (for example allowing a user to close a floating or pinned panel by pressing the UI button that displayed it, ie having that button be a toggle for displaying the panel).

**Comment by louisdh** [comment]
Thanks for reporting this issue. I'll add a public API to close panels in v2.0.

**Comment by louisdh** [comment]
Fixed by d350bb502cec84ed4ea5b6bd5b00f2eefcbc45f5, will ship in v2.0.
