### ISSUE TITLE
Expose move breaks panels

### ISSUE THREAD

**Issue by Kamik423** [louisdh/panelkit#16]
When toggling expose while panels are pinned and then pulling panels the app starts to break down. While in expose apps can be pinned to a different side, then however get blurred into the background. when deactivating expose they return to their original location, but the background is laid out for the panels being pinned to the side were during expose.

Using the example provided (Map and TextView): when both panels are floating and expose is activated the both can (sometimes) be "resized", by pulling the bottom of the panels, which shrinks them down weirdly, even until they vanish. After deactivating expose they return to normal.

**Comment by louisdh** [comment]
Thanks for creating this issue!
I think I've fixed it in 57a3160857d610ad1f693b079f6bba4ca0250cb2, let me know if anything else is broken.
