### ISSUE TITLE
Is it compatible with Objective-C?

### ISSUE THREAD

**Issue by prscX** [louisdh/panelkit#19]
Hi @louisdh,

First of all I would like to appreciate for creating such a nice, cool library.

I wanted to use this in my Objective-C project, does this library provide wrapper for the same?

 #Thanks
Pranav

**Comment by louisdh** [comment]
You should be able to create Swift extensions (for conforming to PanelKit) for your Objective-C classes.

**Comment by gklka** [comment]
Could you give me some hints how can I do it? Almost none of the methods has been exposed to Objective C. I’d be very glad if you could help me a bit in using PanelKit from Objective-C.
