### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by TofPlay** [louisdh/panelkit#2]
Interesting component 🙂
For iOS and macOS projects it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://goo.gl/8AMTfw)
- [Carthage Tutorial: Getting Started](https://goo.gl/9pVzFX)
- [Making Carthage-compatible Frameworks with Swift](https://goo.gl/SzPe8j)
- [Swift Cross Platform Framework](https://goo.gl/XxaJGo) 👍

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by louisdh** [comment]
PanelKit already supports Carthage. The semantic version tag was enough since there are no dependencies. I've now added Carthage instructions and the shield to `README.md`.
