### ISSUE TITLE
Any similar library for Android?

### ISSUE THREAD

**Issue by prscX** [louisdh/panelkit#20]
Hi @louisdh,

First of all I would like to appreciate for creating such a nice, cool library.

Do you know any similar library for Android as well? I have searched a lot but not able to find the same.

Thanks
Pranav

**Comment by louisdh** [comment]
Thanks! There's no Android equivalent that I know of.

**Comment by prscX** [comment]
Thanks @louisdh for the response.

Thanks
Pranav
