### ISSUE TITLE
How to make the dragging work on panels?

### ISSUE THREAD

**Issue by rcholic** [louisdh/panelkit#3]
I've downloaded and run the example in this repo, but the panels show up as the old navigation controller, and I couldn't drag them. Am I missing something obvious for the dragging to work? I've tried to drag the NavigationBar, it does not move.

**Comment by louisdh** [comment]
On what device (and orientation) are you running the example? The default way PanelManager works is to enable floatable panels when the available width > 800pt. Please try on iPad in landscape: you should see a downward arrow button in the navigation bar.

**Comment by rcholic** [comment]
yes, indeed, it works on iPad simulator, but I didn't know it does not work on iPhone simulator. Thanks!
