### ISSUE TITLE
This is amazing!

### ISSUE THREAD

**Issue by LeoNatan** [louisdh/panelkit#8]
I just love this repo, and wanted to share this love with you, and thank you for open sourcing it and seeing the value in open source, despite this being a serious differentiator in your own app!

My "issue" here is that this is not part of UIKit on iPad! Apple introduced the iPad _Pro_, and we still have silly 5x4 SpringBoard grids with such limited UI.

**Comment by louisdh** [comment]
Thanks for the kind words!
Feel free to file a radar to let Apple know you'd like panels in UIKit 🙂.
