### ISSUE TITLE
Add API to present panels in floating or pinned state (without using popover).

### ISSUE THREAD

**Issue by mjrusso** [louisdh/panelkit#9]
First off, @louisdh, thanks for making PanelKit — this is really incredible. :)

I am trying to present a panel in the floating state immediately (i.e., without first presenting the panel in a popover). I've tried a number of techniques; the only thing that comes somewhat close is the following:

```swift

// MARK: - Popover

@IBAction func showMap(_ sender: UIBarButtonItem) {
	showPopover(mapPanelVC, from: sender) {
		if self.mapPanelVC.canFloat {
			self.toggleFloatStatus(for: self.mapPanelVC)
		}
	}		
}

func showPopover(_ vc: UIViewController, from barButtonItem: UIBarButtonItem, completion: (() -> Void)? = nil) {
	vc.modalPresentationStyle = .popover
	vc.popoverPresentationController?.barButtonItem = barButtonItem
	present(vc, animated: true, completion: completion)
}

```

(Although the panel is being presented as a popover, albeit for a very short amount of time.)

The reason that this distinction matters is because I'd like to present a "normal" (non-PanelKit) popover that will allow the user to manage panels, including opening new panels, and potentially closing existing panels. If the panels could start in the floating state immediately, that would make this a lot cleaner.

**Comment by louisdh** [comment]
This is definitely something I want to add to PanelKit, I'll start working on this soon.

**Comment by JacobBoyd** [comment]
You can also use: `self.panelDelegate!.toggleFloatStatus(for: self.parent!.parent as! PanelViewController)` inside of the PanelContentViewController's viewWillAppear to toggle the VC to display in floating mode!

**Comment by alpascual** [comment]
@JacobBoyd Can you clarify your answer how to do that? Where is the `PanelContentViewController`? Thanks man

**Comment by JacobBoyd** [comment]
Sure, the PanelContentViewController here is the VC that is being used to provide the views/content for the panel.  

So for example using: `textPanelVC = PanelViewController(with: textPanelContentVC, contentDelegate: textPanelContentVC, in: self)` you would place the `self.panelDelegate!.toggleFloatStatus(for: self.parent!.parent as! PanelViewController)` inside of textPanelContentVC's viewWillAppear

**Comment by davenquinn** [comment]
Is there any update on this? I'd hope to be able to initialize a panel either directly as a floating panel or pinned to either the right or the left.

**Comment by louisdh** [comment]
PanelManager now has new APIs to set a panel's state without using a popover:
`pin(_ panel: PanelViewController, to side: PanelPinSide, atIndex index: Int)`
`float(_ panel: PanelViewController, at frame: CGRect)`

This is due to ship with PanelKit 2.0.

**Comment by Kamik423** [comment]
maybe add this to the readme, I find myself having to go to the readme for the repeatedly
